version: 3

dotenv:
- .env

tasks:
  build:
  - mkdir -p "$TARGET_PATH"
  - mkdir -p "$TARGET_PATH/plugins"
  - cp assets/* "$TARGET_PATH"
  - cp -u src/bin/Release/OnlineMapHotkey.dll "$TARGET_PATH/plugins"